name: V2AutoUpgrade

on:
  schedule:
    - cron: '*/3 * * * *' # 每3小时运行
  workflow_dispatch: # 允许手动运行

jobs:
  merge-files:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Generate dates and file URLs
      id: dates
      run: |
        YEAR=$(date +%Y)
        MONTH=$(date +%m)
        DAY=$(date +%d)
        FILE_DATE="${YEAR}${MONTH}${DAY}"
        FILE1="https://nodedog.githubrowcontent.com/${YEAR}/${MONTH}/${FILE_DATE}.txt"
        FILE2="https://clashnode.cc/uploads/${YEAR}/${MONTH}/0-${FILE_DATE}.txt"
        FILE3="https://www.miluonode.com/node/${FILE_DATE}-v2ray.txt"
        echo "FILE1=${FILE1}" >> $GITHUB_ENV
        echo "FILE2=${FILE2}" >> $GITHUB_ENV
        echo "FILE3=${FILE3}" >> $GITHUB_ENV

    - name: Download and merge files
      run: |
        curl -s $FILE1 > combined.txt
        curl -s $FILE2 >> combined.txt
        curl -s $FILE3 >> combined.txt

        # 将合并后的文件添加到仓库
        git config --local user.email "1402394430@qq.com"
        git config --local user.name "zjtie"
        git add combined.txt
        git commit -m "Update combined file for $(date +%Y-%m-%d)" || echo "No changes to commit"
        git push
