name: Verify URLs

on:
  workflow_dispatch:

jobs:
  check-files:
    runs-on: ubuntu-latest

    steps:
    - name: 设置环境变量
      run: |
        YEAR=$(date +%Y)
        MONTH=$(printf "%02d" $(date +%m))
        DAY=$(printf "%02d" $(date +%d))
        FILE_DATE="${YEAR}${MONTH}${DAY}"

        FILE1="https://nodedog.githubrowcontent.com/${YEAR}/${MONTH}/${FILE_DATE}.txt"
        FILE2="https://clashnode.cc/uploads/${YEAR}/${MONTH}/0-${FILE_DATE}.txt"

        echo "FILE1=$FILE1" >> $GITHUB_ENV
        echo "FILE2=$FILE2" >> $GITHUB_ENV

    - name: 验证 FILE1 是否有效
      run: |
        echo "Checking FILE1: $FILE1"
        curl -I "$FILE1" || echo "FILE1 无效或不可访问"

    - name: 验证 FILE2 是否有效
      run: |
        echo "Checking FILE2: $FILE2"
        curl -I "$FILE2" || echo "FILE2 无效或不可访问"
